export interface StoreCredential {
  id: string;
  link: string;
  password?: string;
  category: string;
  specialNote?: string;
  profileName?: string;
  clientName?: string;
}

export const presetStoreCredentials: StoreCredential[] = [
  { id: 'sc-1', link: 'https://phoenixforgedwheels.com/', password: 'phoenixforged1!', category: 'Accessories' },
  { id: 'sc-2', link: 'https://talk2tessa.com/', category: 'Others', profileName: 'Pro_wizards', clientName: 'listentolaila' },
  { id: 'sc-3', link: 'https://kasi-commerce-2.myshopify.com/?pb=0', category: 'Digital Products', profileName: 'Wix_buddy', clientName: 'menzi_nkosi' },
  { id: 'sc-4', link: 'https://medikart-3189.myshopify.com/', password: 'thaong', category: 'Medicine', profileName: 'Nasir', clientName: 'ghanknn' },
  { id: 'sc-5', link: 'https://ausbanblanks.com/', password: 'miarto', category: 'Fashion & Apparel', profileName: 'Nasir', clientName: 'astridmcort' },
  { id: 'sc-6', link: 'https://lumabodypro.com/', password: 'dinteu', category: 'Health & Wellness', profileName: 'Pro_wizards', clientName: 'frankmobley428' },
  { id: 'sc-7', link: 'https://entrenando.cl/', category: 'Fitness & Health', profileName: 'expo_web', clientName: 'jorge_jottar' },
  { id: 'sc-8', link: 'https://www.cangroo-cangroo.com/', category: 'Fashion & Apparel', profileName: 'shopify_manir', clientName: 'georgerobu33' },
  { id: 'sc-9', link: 'https://apeaxfilms.com/', password: 'neeffi', category: 'Accessories', profileName: 'expo_web', clientName: 'detailersmoveme' },
  { id: 'sc-10', link: 'https://www.nordicpirates.com/', category: 'Sports', profileName: 'Ecom_geeky', clientName: 'nordicpirategam' },
  { id: 'sc-11', link: 'https://aruta-jp.com/', category: 'Accessories', specialNote: 'Travel Accessories', profileName: 'webbrave_', clientName: 'mari_artisan' },
  { id: 'sc-12', link: 'https://printmeonline.com/', category: 'Fashion & Apparel', profileName: 'expo-web', clientName: 'dudem6' },
  { id: 'sc-13', link: 'https://luckyhits.shop/', category: 'Sports', specialNote: 'Trading Card Games', profileName: 'expo-web', clientName: 'acigji' },
  { id: 'sc-14', link: 'https://ketolite.net/', category: 'Health & Wellness', profileName: 'three-web', clientName: 'crysyd' },
  { id: 'sc-15', link: 'https://havocpowersports.com/', category: 'Bike', profileName: 'manir', clientName: 'golfcartpartz' },
  { id: 'sc-16', link: 'https://glowic-wonder-growth-oil.myshopify.com/', password: 'gecree', category: 'Hair Oil', profileName: 'expo-web', clientName: 'stankosters' },
  { id: 'sc-17', link: 'https://thebestreadingsystem.com/', category: 'Book', profileName: 'expo-web', clientName: 'sineal' },
  { id: 'sc-18', link: 'https://willboardman.co.uk/', category: 'Service', specialNote: 'BBA Accounting Course Sell', profileName: 'pro_wizards', clientName: 'willboardman1' },
  { id: 'sc-19', link: 'https://nextleadersllc.com/', category: 'Kids & Baby Products', specialNote: 'kids clothing', profileName: 'wixbuddy_fiverr', clientName: 'sg7millions0722' },
  { id: 'sc-20', link: 'https://valcrestcollection.com', category: 'Jewelry', specialNote: 'Mens jewellery', profileName: 'wixbuddy_fiverr', clientName: 'davidluke643' },
  { id: 'sc-21', link: 'https://shabasa.store', category: 'Kids & Baby Products', specialNote: 'Multi-product dropshipping store', profileName: 'Manir', clientName: 'sumiya2026' },
  { id: 'sc-22', link: 'https://branaleather.com/', category: 'Fashion & Apparel', specialNote: 'Leather Bag', profileName: 'pro_wizards', clientName: 'brana_leather' },
  { id: 'sc-23', link: 'https://lekker-2b-lekker.myshopify.com', password: 'tahmaw', category: 'Restaurant', specialNote: 'tradition Beef and Chips', profileName: 'expo_web', clientName: 'garethrichard' },
  { id: 'sc-24', link: 'https://7y9cti-gy.myshopify.com', password: 'rtigew', category: 'Sports', specialNote: 'golf', profileName: 'manir', clientName: 'jbooth_87' },
  { id: 'sc-25', link: 'https://sharmacarwash.be', category: 'Service', specialNote: 'Car wash subscripton', profileName: 'expo_web', clientName: 'sunnysinghs' },
  { id: 'sc-26', link: 'https://kunoxygen.com/', category: 'Fitness & Health', profileName: 'Shopify_Manir', clientName: 'huneidi' },
  { id: 'sc-27', link: 'https://living4vitality.com/', category: 'Health & Wellness', profileName: 'pro wizards', clientName: 'rolepax' },
  { id: 'sc-28', link: 'https://caring-gate-2.myshopify.com/', category: 'Health & Wellness', profileName: 'Pro wizards', clientName: 'derekgillespie' },
  { id: 'sc-29', link: 'https://shop.echovalleyhq.com/', category: 'Fashion & Apparel', profileName: 'Champ_squad', clientName: 'wisewander' },
  { id: 'sc-30', link: 'https://furcleanerpro.com/', category: 'Pet Products', profileName: 'shopify_manir_Fiverr', clientName: 'chinedum007' },
  { id: 'sc-31', link: 'https://vyralabs.health/', category: 'Fitness & Health', specialNote: 'Health test kit', profileName: 'pro_wizards', clientName: 'massimotrava21' },
  { id: 'sc-32', link: 'Fitestore', category: 'Fitness & Health', profileName: 'webbrave', clientName: 'aronthanh' },
  { id: 'sc-33', link: 'Take Kare | Méthode d’organisation et de gestion du temps', category: 'Health & Wellness', specialNote: 'Life Care', profileName: 'Shopify_Nasir', clientName: 'takekare (Mathilde )' },
  { id: 'sc-34', link: 'Purify Paw™ | Smart Pet Grooming Tools for Clean & Happy Pets – Petly', category: 'Pet Products', specialNote: 'Pet Product(Single Store)', profileName: 'expo_web', clientName: 'abasinhakimi' },
  { id: 'sc-35', link: 'Caribekit – Premium Guest Amenities for Hotels, Resorts & Airbnbs', category: 'Beauty & Skincare', clientName: 'jeroenhoijtink' },
  { id: 'sc-36', link: 'Kenetix Recovery Gear Australia | Boots, Massage Pads & Straps', category: 'Fitness & Health', specialNote: 'Fitness and Health', profileName: 'webbrave', clientName: 'Sammoves' },
  { id: 'sc-37', link: 'https://bandcwholesale-2.myshopify.com/', category: 'Light', profileName: 'expo_web_Fiverr' },
  { id: 'sc-38', link: 'https://i501sp-fe.myshopify.com/', password: 'theabu', category: 'Others', profileName: 'expo_web_Fiverr', clientName: 'rpon2701' },
  { id: 'sc-39', link: 'https://www.lrsperformance.com', password: 'iaglia', category: 'Others', profileName: 'expo_web_Fiverr', clientName: 'lrsperformance' },
  { id: 'sc-40', link: 'https://06j4qs-py.myshopify.com/', password: 'gahjoh', category: 'Beauty & Skincare', profileName: 'Champ_squad', clientName: 'kel007' },
  { id: 'sc-41', link: 'https://www.katyals.in/', password: 'niteun', category: 'Fashion & Apparel', profileName: 'pro_wizards', clientName: 'mridulkatyal' },
  { id: 'sc-42', link: 'https://www.gymhook.uk/', password: 'goboni', category: 'Fashion & Apparel', profileName: 'pro_wizards', clientName: 'djdibin' },
  { id: 'sc-43', link: 'https://ez-highlights.myshopify.com/', password: 'yureas', category: 'Beauty & Skincare', profileName: 'wix_buddy', clientName: 'shahinkforoutan' },
  { id: 'sc-44', link: 'https://solarecovery.com.au/', password: 'JAM123', category: 'Electronics & Gadgets', profileName: 'Webbrave Fiverr', clientName: 'jnass301' },
  { id: 'sc-45', link: 'https://inheritanceapparel.shop/', password: 'IAMERCH$2026', category: 'Fashion & Apparel', profileName: 'Manir', clientName: 'ia_vendor' },
  { id: 'sc-46', link: 'https://backtosomaliabook.com', password: 'bozows', category: 'Others', profileName: 'wix_buddy', clientName: 'mac_publishing8' },
  { id: 'sc-47', link: 'https://www.aquaallure.com/', category: 'Fashion & Apparel', profileName: 'eCom_Geeky_Fiverr', clientName: 'aries10' },
  { id: 'sc-48', link: 'https://keithmillerministries.org/', category: 'Digital Products', profileName: 'Shopify_Manir_Fiver', clientName: 'keithsf' },
  { id: 'sc-49', link: 'https://ixps0b-md.myshopify.com/', password: '123', category: 'Perfume', profileName: 'expo_web', clientName: 'nikasawyers' },
  { id: 'sc-50', link: 'https://wf9qeu-fm.myshopify.com/', password: '123', category: 'Service', profileName: 'expo_web', clientName: 'kenny1241' },
  { id: 'sc-51', link: 'https://oykami.ch/', category: 'Kids & Baby Products', profileName: 'Tech_weav', clientName: 'manuela1212' },
  { id: 'sc-52', link: 'https://crafthappensco.com/', category: 'Custom Controller', profileName: 'expo_web_Fiverr', clientName: 'crafthappensco' },
  { id: 'sc-53', link: 'https://maranah.com/', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 's_tausif' },
  { id: 'sc-54', link: 'https://www.the-mvmnt-cllctv.com/', category: 'GYM Belt', profileName: 'expo_web', clientName: 'mvmnt_cllctv' },
  { id: 'sc-55', link: 'https://www.rasmparfums.com/', category: 'Perfume', profileName: 'pro wizards', clientName: 'asifhashmi491' },
  { id: 'sc-56', link: 'https://veyno.co/', category: 'Service', profileName: 'Pro_wizards', clientName: 'jaydenleao' },
  { id: 'sc-57', link: 'https://luxvita.uk/', category: 'Suppliment', profileName: 'pro-wizards', clientName: 'aaron3811' },
  { id: 'sc-58', link: 'https://apotheca-mediterra.myshopify.com/', category: 'Frutis', profileName: 'Champ_squad', clientName: 'batonfevver' },
  { id: 'sc-59', link: 'https://kittydine.co/', category: 'Pet Products', profileName: 'pro wizards', clientName: 'cathome1990' },
  { id: 'sc-60', link: 'https://doctorbrandt-shop.com/', password: 'theoda', category: 'Fashion & Apparel', profileName: 'expo_web_Fiverr', clientName: 'ale_gerosa' },
  { id: 'sc-61', link: 'https://princyxoxo.myshopify.com/', password: 'dowdru', category: 'Fashion & Apparel', profileName: 'pro_wizards', clientName: 'princyxoxo' },
  { id: 'sc-62', link: 'https://www.stitchandjersey.com/pages/about-us', category: 'Sports', profileName: 'expo_web_Fiverr', clientName: 'astaria' },
  { id: 'sc-63', link: 'https://therootmd.com/', category: 'Beauty & Skincare', profileName: 'pro_wizards', clientName: 'marismoore' },
  { id: 'sc-64', link: 'https://upzmm1-uv.myshopify.com/', password: 'lahtwa', category: 'Fashion & Apparel', profileName: 'Ecom_Gacky', clientName: 'petersargison' },
  { id: 'sc-65', link: 'https://galuarte.store/', category: 'Fashion & Apparel', profileName: 'pro_wizards', clientName: 'RaicesPR26!' },
  { id: 'sc-66', link: 'https://real-clothing-9857.myshopify.com/', password: 'dajuly', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 'gavinj47' },
  { id: 'sc-67', link: 'https://drinkislandvibe.com/', category: 'Drinks', profileName: 'pro wizards', clientName: 'kennyjohnson100' },
  { id: 'sc-68', link: 'https://exclusivecarmats.com/', category: 'Car', profileName: 'expo_web', clientName: 'olevannassau' },
  { id: 'sc-69', link: 'https://1tabcs-4j.myshopify.com/', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 'calvinbennett12' },
  { id: 'sc-70', link: 'https://icelltechnology.store/', category: 'Electronics & Gadgets', profileName: 'shopify_manir', clientName: 'qassimbachodia' },
  { id: 'sc-71', link: 'https://blingignition.com', password: 'inaoli', category: 'Accessories', profileName: 'eCom_Geeky', clientName: 'rochellebrown1' },
  { id: 'sc-72', link: 'https://lovelore.design/', category: 'Fashion & Apparel', profileName: 'Webbrave', clientName: 'honeyblossoms' },
  { id: 'sc-73', link: 'https://duhmaan.com', category: 'Accessories', profileName: 'expo_web', clientName: 'ahmedmotasem640' },
  { id: 'sc-74', link: 'https://bkparfum.com', category: 'perfume', profileName: 'Wix-buddy', clientName: 'baki31' },
  { id: 'sc-75', link: 'https://nichefragrance.co.za', password: 'oclaug', category: 'Perfume', profileName: 'expo_web', clientName: 'mbaraknahdi497' },
  { id: 'sc-76', link: 'https://fisecs-1t.myshopify.com', category: 'Pet Products', profileName: 'Manir', clientName: 'thelazer' },
  { id: 'sc-77', link: 'https://vybeewellness.com/', category: 'Food', profileName: 'expo_web', clientName: 'hakimi_vybee' },
  { id: 'sc-78', link: 'https://wmvimw-qk.myshopify.com/', password: 'tahxeb', category: 'Service', profileName: 'pro_wizards', clientName: 'bradb84' },
  { id: 'sc-79', link: 'https://www.jadan.ca/', category: 'Beauty & Skincare', profileName: 'pro_wizards', clientName: 'jadanshop' },
  { id: 'sc-80', link: 'https://gogutterguy.com/', category: 'Service Oriented', profileName: 'wixbuddy_fiverr', clientName: 'chrisspring' },
  { id: 'sc-81', link: 'https://scratchgard-precut.com/', password: 'gohyaw', category: 'Non E-Commerce', profileName: 'Ecom_geeky', clientName: 'rahulbathija' },
  { id: 'sc-82', link: 'https://soundproofingking.co.uk/', category: 'E-Commerce', profileName: 'webbrave', clientName: 'carterfx' },
  { id: 'sc-83', link: 'https://www.verdelleherbs.com/', category: 'Others', profileName: 'wix_buddy_Fiverr', clientName: 'safwanghani9' },
  { id: 'sc-84', link: 'https://merengetirhinosafari.com/', category: 'Service', profileName: 'three_web', clientName: 'merengeti2024' },
  { id: 'sc-85', link: 'https://www.brasslux.com', category: 'Kictchen Accessories', profileName: 'expo_web_Fiverr' },
  { id: 'sc-86', link: 'https://www.bedmode.co.uk/', category: 'Home & Living', profileName: 'tech_weav' },
  { id: 'sc-87', link: 'https://mikaatelier.com/', category: 'Fashion & Apparel', profileName: 'webbrave' },
  { id: 'sc-88', link: 'https://www.akai-london.co.uk/', category: 'Jewelry', profileName: 'Bits wise fiverr' },
  { id: 'sc-89', link: 'https://mykelou.com/', category: 'Kids & Baby Products', profileName: 'Tech_weav_Fiver' },
  { id: 'sc-90', link: 'https://panda-treasure-quest.myshopify.com/', password: 'meskew', category: 'Service' },
  { id: 'sc-91', link: 'https://v6witc-uv.myshopify.com/', category: 'Printing' },
  { id: 'sc-92', link: 'https://stay-ready-training.myshopify.com/', password: 'peffaw', category: 'Tactical' },
  { id: 'sc-93', link: 'https://www.flightclub360.com/', password: 'usiglo', category: 'Giveaway' },
  { id: 'sc-94', link: 'https://modeltique.com/', category: 'Fashion & Apparel' },
  { id: 'sc-95', link: 'https://wellnesspeptidesusa.com/', category: 'Peptides' },
  { id: 'sc-96', link: 'https://everpaws.co/', password: 'daynao', category: 'Pet Products' },
  { id: 'sc-97', link: 'https://www.numbnectar.store/', category: 'Others' },
  { id: 'sc-98', link: 'https://ebbrwa-9f.myshopify.com/?_ab=0&_fd=0&_sc=1&preview_theme_id=145033560234', category: 'Food' },
  { id: 'sc-99', link: 'https://valuepricemall-vpm.myshopify.com/?_ab=0&_fd=0&_sc=1&key=b387323a9c6795060179af280a6d74945ca15f423173b49c13b358db2687a7b2&preview_theme_id=188196421705', category: 'Others' },
  { id: 'sc-100', link: 'https://0f0ydr-v4.myshopify.com/', password: 'maureu', category: 'Pet Products' },
  { id: 'sc-101', link: 'https://racingdatadirect-com-2.myshopify.com/', password: 'saffox', category: 'Accessories' },
  { id: 'sc-102', link: 'https://activemeals.com.au/', password: 'ActiveMeals', category: 'Restaurant', profileName: 'ecom_geeky', clientName: 'rsrewards' },
  { id: 'sc-103', link: 'http://xtremewear.net/', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 'xtremewear' },
  { id: 'sc-104', link: 'https://www.desvergue.com/', password: 'gawdro', category: 'Sports', specialNote: 'CARD GAME', profileName: 'eCom_Geeky', clientName: 'redbull357' },
  { id: 'sc-105', link: 'https://thetechfactory.shop/', category: 'Electronics & Gadgets', specialNote: 'TECH PRODUCTS- WHOLESALE', profileName: 'three_web', clientName: 'ajsno2' },
  { id: 'sc-106', link: 'https://sg11mm-vm.myshopify.com/', category: 'Fitness & Health', specialNote: 'FITNESS FESTIVAL EVENT', profileName: 'expo_web', clientName: 'venustolesbey' },
  { id: 'sc-107', link: 'https://thefemininevault.com/', category: 'Digital Products', profileName: 'pro-wizards', clientName: 'amoservices' },
  { id: 'sc-108', link: 'https://ayropet.com/', category: 'Pet Products', specialNote: 'Pet Suppliment', profileName: 'Shopify_Manir', clientName: 'ayropet2026' },
  { id: 'sc-109', link: 'https://runninref.com/', category: 'Sports', specialNote: 'Course Selling Website', profileName: 'expo_web', clientName: 'therunninref' },
  { id: 'sc-110', link: 'https://97r1rp-fy.myshopify.com/', password: 'steith', category: 'Electronics & Gadgets', specialNote: 'Watch Shop', profileName: 'Ecom_geeky', clientName: 'hyper_souza' },
  { id: 'sc-111', link: 'https://movaya.fr/', password: 'ahngia', category: 'Fashion & Apparel', specialNote: 'Heat-Free Hairstyle Rollers', profileName: 'Champ_squad', clientName: 'naomi_louis_a' },
  { id: 'sc-112', link: 'https://babyriot.co', password: 'admin', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 'ninatruong04104' },
  { id: 'sc-113', link: 'https://www.nklashes.ch/', password: 'admin', category: 'Beauty & Skincare', profileName: 'pro_wizards', clientName: 'rinorkastrati' },
  { id: 'sc-114', link: 'https://r3main.myshopify.com/', password: 'aglahy', category: 'Fashion & Apparel', profileName: 'ecom_geeky', clientName: 'pamela_kristen' },
  { id: 'sc-115', link: 'https://shop.chargerzilla.com/', category: 'Electronics & Gadgets', profileName: 'expo_web_Fiverr', clientName: 'techuser2020' },
  { id: 'sc-116', link: 'https://rauchmelder-profishop-de.myshopify.com/', password: 'newbra', category: 'Electronics & Gadgets', profileName: 'expo_web', clientName: 'rateballaf' },
  { id: 'sc-117', link: 'https://dapsfashion.com/', category: 'Fashion & Apparel', profileName: 'dev_pioneer', clientName: 'directautoplugs' },
  { id: 'sc-118', link: 'https://lavishoils.com/', password: 'admin', category: 'Beauty & Skincare', profileName: 'pro_wizards_Fiverr', clientName: 'ptpllc' },
  { id: 'sc-119', link: 'https://neventrylabs.com/', password: 'admin', category: 'Landing Page', profileName: 'pro_wizards', clientName: 'felipeveit' },
  { id: 'sc-120', link: 'https://nancyfloraverde.com/', category: 'Frutis', profileName: 'Webbrave', clientName: 'chantalturgeon' },
  { id: 'sc-121', link: 'https://usabunkersupply.com/', category: 'Others', profileName: 'pro_wizards', clientName: 'toddstump' },
  { id: 'sc-122', link: 'https://blaezfaceshop.myshopify.com/', password: 'MaDi', category: 'Fashion & Apparel', specialNote: 'Clothing', profileName: 'pro_wizards', clientName: 'manuelblaetz' },
  { id: 'sc-123', link: 'https://anti-reform.com/', password: 'Karyn121', category: 'Fashion & Apparel', profileName: 'Champ_squad', clientName: 'karyn_thom' },
  { id: 'sc-124', link: 'https://www.beautytouch-toulouse.com/', category: 'Beauty & Skincare', profileName: 'webbrave', clientName: 'orienda74' },
  { id: 'sc-125', link: 'https://hlstore.ae/', category: 'Accessories', specialNote: 'Bag', profileName: 'Ecom_geeky', clientName: 'jasaami' },
  { id: 'sc-126', link: 'https://nexorapowerbanks.com/', category: 'Electronics & Gadgets', profileName: 'expo_web', clientName: 'nexorapowerbank' },
  { id: 'sc-127', link: 'https://treatzcartel.co.uk/', category: 'Others', specialNote: 'candy site', profileName: 'Webbrave', clientName: 'oyounas223344' },
  { id: 'sc-128', link: 'https://maison-pasha.com/', password: 'pohble', category: 'Pet Products', profileName: 'pro wizards', clientName: 'patriciaaiguade' },
  { id: 'sc-129', link: 'https://the-self-studio-1.myshopify.com/', password: 'lushea', category: 'Fitness & Health', profileName: 'Webbrave', clientName: 'jacobsalley' },
  { id: 'sc-130', link: 'https://www.backriverblends.com/', category: 'Others', specialNote: 'food items', profileName: 'shopify_manir', clientName: 'camiari_12918' },
  { id: 'sc-131', link: 'https://www.verdelleherbs.com', password: 'alempu', category: 'Beauty & Skincare', profileName: 'wix_buddy_Fiverr', clientName: 'safwanghani9' },
  { id: 'sc-132', link: 'https://gummy-tech.myshopify.com/', password: 'teitre', category: 'Electronics & Gadgets', profileName: 'Tech_suite', clientName: 'traton780' },
  { id: 'sc-133', link: 'https://travel-esim-3.myshopify.com/', password: 'demo301', category: 'E-sim', profileName: 'wixbuddy', clientName: 'telco_guru' },
  { id: 'sc-134', link: 'https://www.cangroo-cangroo.com/', category: 'Bag', profileName: 'Shopify Manir', clientName: 'georgerobu33' },
  { id: 'sc-135', link: 'https://7gy2awnkscnx5bl9-29109387312.shopifypreview.com', category: 'Fashion & Apparel', profileName: 'new_dev', clientName: 'davis1962' },
  { id: 'sc-136', link: 'https://chosentorise.com', password: 'ifleey', category: 'Fashion & Apparel', profileName: 'eCom_Geeky', clientName: 'xtravensky98' },
  { id: 'sc-137', link: 'https://ih7puig6zr4ctfgf-100330176884.shopifypreview.com', category: 'textiles', profileName: 'Webbrave', clientName: 'rbamroo' },
  { id: 'sc-138', link: 'https://6mtd5k-pz.myshopify.com/', password: 'abohpu', category: 'Car accesories', profileName: 'tech_plex', clientName: 'ch_jacob' },
  { id: 'sc-139', link: 'https://emoe-co.com/', password: 'itreen', category: 'Woman Dress accessories', profileName: 'pro_wizards', clientName: 'poiricx' },
  { id: 'sc-140', link: 'https://da5hqf-qq.myshopify.com/', password: 'staymp', category: 'Suppliment', profileName: 'tech_wonder', clientName: 'robalbert438' },
  { id: 'sc-141', link: 'https://amonefragrance.com/', category: 'Perfume', specialNote: 'Bundle, custom perfume build functionality', profileName: 'Manir', clientName: 'amonebln' },
  { id: 'sc-142', link: 'https://uethz2-qw.myshopify.com/', password: '9', category: 'Furniture', specialNote: 'Compare functionality build', profileName: 'Pro wizard', clientName: 'nagycsongor' },
  { id: 'sc-143', link: 'https://bloomshine.com.sg/', category: 'Flower & Accessories', profileName: 'Wedev_pro', clientName: 'gerevasan' },
  { id: 'sc-144', link: 'https://vyue.nl/', category: 'Sunglass', specialNote: 'Choose Glass Functionality for Prescription', profileName: 'Manir', clientName: 'yousifmisho' },
  { id: 'sc-145', link: 'https://expeditionrally.com/', category: 'Bike', profileName: 'tech_weav', clientName: 'esthercases' },
  { id: 'sc-146', link: 'https://kitfix.com/', category: 'Artwork' },
  { id: 'sc-147', link: 'https://orlibeautybar.com/', category: 'Beauty & Skincare', specialNote: 'live store client get sell' },
  { id: 'sc-148', link: 'https://furryflow.org/', category: 'Pet Products' },
  { id: 'sc-149', link: 'https://www.mmlashes-beautyshop.de/', category: 'Beauty & Skincare', specialNote: 'live store client get sell' },
  { id: 'sc-150', link: 'https://axyon.com.au/', category: 'Electronics & Gadgets', specialNote: 'live store client get sell' },
  { id: 'sc-151', link: 'https://iconichairlux.com/', category: 'Beauty & Skincare', specialNote: 'live store client get sell' },
  { id: 'sc-152', link: 'https://shoppreppypearl.com/', category: 'Fashion & Apparel', specialNote: 'live store client get sell' },
  { id: 'sc-153', link: 'https://berichplanner.shop/', category: 'Others', specialNote: 'live store client get sell' },
  { id: 'sc-154', link: 'https://creationsbysuheily.myshopify.com/', password: 'thowff', category: 'Others', profileName: 'infini_tech0', clientName: 'suheilycaldero' },
  { id: 'sc-155', link: 'https://loomi-6316.myshopify.com/', password: 'thogli', category: 'Kids & Baby Products', profileName: 'pandascout', clientName: 'jeroenherms996' },
  { id: 'sc-156', link: 'https://comickazcollectibles.com/', password: 'Jack$onville -96', category: 'Others', profileName: 'pro_wizards', clientName: 'jaxbwaters91' },
  { id: 'sc-157', link: 'https://wia11a-h6.myshopify.com/', password: 'skubre', category: 'Others', profileName: 'Wix_Buddy', clientName: 'cmerc3' },
  { id: 'sc-158', link: 'https://9x1img-dm.myshopify.com/', password: 'gowbai', category: 'Health & Wellness', profileName: 'pro_wizards', clientName: 'zabee367' },
  { id: 'sc-159', link: 'https://whitehippogolf.com/', category: 'Fashion & Apparel', profileName: 'dev_pioneer', clientName: 'white_hippo' },
  { id: 'sc-160', link: 'https://whiskerandwilde.com/', password: 'gayfli', category: 'Pet Products', profileName: 'expo_web_Fiverr' },
  { id: 'sc-161', link: 'https://benjaminmaxwell.myshopify.com', password: 'liatro', category: 'Home & Living', profileName: 'three_web' },
  { id: 'sc-162', link: 'https://maisonlayia.com/', category: 'Fashion & Apparel', profileName: 'Shopify_Manir_Fiverr' },
  { id: 'sc-163', link: 'https://www.forgempire.com/', password: 'skayli', category: 'Jewelry', profileName: 'Shopify_Manir_Fiverr' },
  { id: 'sc-164', link: 'https://www.loosethread.co.za/', category: 'Fashion & Apparel', profileName: 'wix_buddy' },
  { id: 'sc-165', link: 'https://www.billdelivers.com.au/', category: 'Others', profileName: 'Shopify_Manir_Fiverr' },
  { id: 'sc-166', link: 'https://linkedcharlotte.com/', category: 'Fashion & Apparel', profileName: 'Shopify_Manir' },
  { id: 'sc-167', link: 'https://maisonpasha.myshopify.com/', password: 'pohble', category: 'Pet Products', profileName: 'pro-wiz' },
  { id: 'sc-168', link: 'https://modithelabel.com/', category: 'Fashion & Apparel', profileName: 'pro-wiz' },
  { id: 'sc-169', link: 'https://kaz-decor.myshopify.com/', password: 'skoday', category: 'Home & Living', profileName: 'WixBuddy' },
  { id: 'sc-170', link: 'https://plstkhome.com/', category: 'Home & Living', profileName: 'eCom_Geeky Fiverr' },
  { id: 'sc-171', link: 'https://summers-sweetery.myshopify.com/', password: 'thaura', category: 'Others', profileName: 'eCom_Geeky Fiverr' },
  { id: 'sc-172', link: 'https://maisonlayia.com', category: 'Fashion & Apparel', profileName: 'Shopify_Manir' },
  { id: 'sc-173', link: 'https://www.disorderlyconduction.com/', category: 'Electronics & Gadgets', profileName: 'expo_web' },
  { id: 'sc-174', link: 'https://shop.snoremuch.com/', category: 'Others', profileName: 'Webbrave Fiverr' },
  { id: 'sc-175', link: 'https://9dm1pc-41.myshopify.com/', password: 'reibre', category: 'Others', profileName: 'Webbrave Fiverr' },
  { id: 'sc-176', link: 'https://puropet.es/', category: 'Pet Products', profileName: 'Webbrave Fiverr' },
  { id: 'sc-177', link: 'https://sendagift.shop/', category: 'Health & Wellness', profileName: 'pro-wiz' },
  { id: 'sc-178', link: 'https://xn--sllskapet-v2a.se/', category: 'Others', profileName: 'pro-wizards' },
  { id: 'sc-179', link: 'https://shop.usagivr.com/', password: 'deodre', category: 'Electronics & Gadgets', profileName: 'three_web' },
  { id: 'sc-180', link: 'https://cookieasy-shop.com/', password: 'riceig', category: 'Kictchen Accessories', profileName: 'pro-wizards' },
  { id: 'sc-181', link: 'https://whippduk.co.uk/', category: 'Car accesories', profileName: 'eCom_Geeky Fiverr' },
  { id: 'sc-182', link: 'https://www.elureaskin.com/', password: 'Triplepack1', category: 'Beauty & Skincare', profileName: 'Tech_weav' },
  { id: 'sc-183', link: 'https://aandsrefrigerationboxes.com/', category: 'Others', profileName: 'eCom_Geeky Fiverr' },
  { id: 'sc-184', link: 'https://comfortthroughcancer.com/', password: 'gahnto', category: 'Health & Wellness', profileName: 'pro-wiz' },
  { id: 'sc-185', link: 'https://topteile24.de/', category: 'Car accesories', profileName: 'Shopify_Manir_Fiverr' },
  { id: 'sc-186', link: 'https://thlstudio.com/', category: 'Fashion & Apparel', profileName: 'Shopify_Manir_Fiverr' },
  { id: 'sc-187', link: 'https://valuablethreads.com/', category: 'Fashion & Apparel', profileName: 'expo_web_Fiverr' },
  { id: 'sc-188', link: 'https://www.bxmfitness.com/', password: 'bathea', category: 'Fashion & Apparel', profileName: 'expo_web_Fiverr' },
  { id: 'sc-189', link: 'https://aardvarksfuturescientists.com/', category: 'Kids & Baby Products', profileName: 'tech_forge1' },
  { id: 'sc-190', link: 'https://www.smashfactory.se/', password: 'ahtegi', category: 'Fitness & Health', profileName: 'pro-wiz' },
  { id: 'sc-191', link: 'https://www.cabana-miami.com/', category: 'Furniture', profileName: 'Webbrave Fiverr' },
  { id: 'sc-192', link: 'babodim.com', category: 'Others', profileName: 'Three_Web' },
  { id: 'sc-193', link: 'hokuhandcrafts.com', password: 'paifri', category: 'Home & Living', profileName: 'Three_Web' },
  { id: 'sc-194', link: 'binturong.my', category: 'Others' },
  { id: 'sc-195', link: 'luvinitypublishing.com', password: 'yauyah', category: 'Fashion & Apparel' },
  { id: 'sc-196', link: 'platinummarineproducts.com', password: '$platinum$', category: 'Others' },
  { id: 'sc-197', link: 'genesismembermeals.com', category: 'Others' },
  { id: 'sc-198', link: 'aiery.co', category: 'Fashion & Apparel' },
  { id: 'sc-199', link: 'uikvq9-yt.myshopify.com', password: 'Tokyo', category: 'Fashion & Apparel' },
  { id: 'sc-200', link: 'coco-bar.com', category: 'Chocolate' },
  { id: 'sc-201', link: 'www.dockgentleman.com', category: 'Fashion & Apparel' },
  { id: 'sc-202', link: 'theroomstoreaz.com', password: 'yemugo', category: 'Furniture', specialNote: 'Dev Empire', clientName: 'yomtovmen' },
  { id: 'sc-203', link: 'www.veralosso.com', category: 'Fashion & Apparel', specialNote: 'Prowizard', clientName: 'mohamedaziz94' },
  { id: 'sc-204', link: '5qjtec-ng.myshopify.com/password', password: 'piflaw', category: 'Others', specialNote: 'Expoweb', clientName: 'milenikolikj580' },
  { id: 'sc-205', link: 'ouwhj1s2gkahv75j-68681302203.shopifypreview.com', category: 'Industrial, Equipment solutions', specialNote: 'https://proventuremarketplace.com/', profileName: 'expo_web', clientName: 'proventuremarke & ericak1990' },
  { id: 'sc-206', link: 'glossy-twins-3.myshopify.com/', password: 'eamime', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 'latanya_gilbert' },
  { id: 'sc-207', link: 'juiznk-c9.myshopify.com/', password: 'uwaily', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 'danielsamuel860' },
  { id: 'sc-208', link: 'bailey-saddlery-tack-2.myshopify.com/', password: 'doskas', category: 'Others' },
  { id: 'sc-209', link: 'www.mahoro.co/', category: 'Pet Products' },
  { id: 'sc-210', link: 'seher.cz/', category: 'Home & Living' },
  { id: 'sc-211', link: 'y9jnke-ui.myshopify.com/', password: 'tahfre', category: 'Custom Controller' },
  { id: 'sc-212', link: 'tressca.com/', category: 'GYM Belt' },
  { id: 'sc-213', link: 'turbobitez.myshopify.com/', password: 'turbobitez', category: 'Pre Workout Gummy' },
  { id: 'sc-214', link: 'palzandco.com/', category: 'Pet Products' },
  { id: 'sc-215', link: 'www.thebonefarm.shop/', category: 'Fossil show' },
  { id: 'sc-216', link: 'pronerv.com/', category: 'Suppliment' },
  { id: 'sc-217', link: 'uikvq9-yt.myshopify.com/', password: 'Tokyo', category: 'Fashion & Apparel', specialNote: 'Main Login', clientName: 'cbgo1976' },
  { id: 'sc-218', link: 'gkmhv1-yc.myshopify.com/', password: 'taohia', category: 'Others', specialNote: 'Three_web', clientName: 'lora1989' },
  { id: 'sc-219', link: 'chelseamats.com/', category: 'Others', profileName: 'eCom_Geeky', clientName: 'cbrphotography' },
  { id: 'sc-220', link: 'a2bstudiofl.myshopify.com/', category: 'Home & Living', profileName: 'Shopify Manir', clientName: 'anthonymidge136' },
  { id: 'sc-221', link: 'www.lifeperformancenutrition.com/', category: 'Suppliment', profileName: 'Shopify Manir', clientName: 'tracyb1' },
  { id: 'sc-222', link: 'up65qs-yb.myshopify.com/', password: 'osatah', category: 'Others', specialNote: 'seruiz05', profileName: 'expo_web' },
  { id: 'sc-223', link: 'tycoontea.com/', category: 'Others' },
  { id: 'sc-224', link: 'true-north-studio-3.myshopify.com/', password: 'xawlda', category: 'GYM Belt' },
  { id: 'sc-225', link: 'derma-stamp-3.myshopify.com/', password: 'ureusk', category: 'Electronics & Gadgets', profileName: 'expo_web', clientName: 'reubentheron' },
  { id: 'sc-226', link: 'kinangph.myshopify.com/', password: 'yeebre', category: 'Home & Living', profileName: 'pro_wizards', clientName: 'mareli1019' },
  { id: 'sc-227', link: 'sensaandco.com/', password: '2pacLucky66', category: 'Jewelry', profileName: 'pro_wizards', clientName: 'tydotuk' },
  { id: 'sc-228', link: 'graceflowers.com/', category: 'Fashion & Apparel', profileName: 'wix_buddy_fiverr', clientName: 'tamarbeauty' },
  { id: 'sc-229', link: 'the-perfect-guitar-2.myshopify.com/', password: 'meishi', category: 'Music', profileName: 'expo_web', clientName: 'boostrocket' },
  { id: 'sc-230', link: 'fmjbeardcare.com/', password: 'Jesus', category: 'Beauty & Skincare', profileName: 'Webbrave_Fiverr', clientName: 'fmjorganics123' },
  { id: 'sc-231', link: 'printloop3d.com/', category: 'Accessories', profileName: 'wix_buddy', clientName: 'amiltonhonorio' },
  { id: 'sc-232', link: 'www.naturellegrow.com/', category: 'Beauty & Skincare', profileName: 'pro_wizards', clientName: 'rsan319951' },
  { id: 'sc-233', link: 'www.savannabros.com/', category: 'Fashion & Apparel', profileName: 'pro_wizards', clientName: 'kevancooper' },
  { id: 'sc-234', link: 'uwaia.com/', category: 'Beauty & Skincare', profileName: 'pro_wizards', clientName: 'guppietv' },
  { id: 'sc-235', link: 'turbobitez.myshopify.com/', password: 'turbobitez', category: 'Fitness & Health', profileName: 'wix_buddy', clientName: 'ziad_azabi23' },
  { id: 'sc-236', link: 'vehicare-2.myshopify.com/', category: 'Service', profileName: 'expo_web', clientName: 'jm50505' },
  { id: 'sc-237', link: 'mburrzd.com/', category: 'Others', profileName: 'three_web', clientName: 'impacttechsol' },
  { id: 'sc-238', link: 'www.shopsylmora.com/', category: 'Woman Dress accessories', profileName: 'expo_web', clientName: 'curtispierre744' },
  { id: 'sc-239', link: 'kaz-decor.myshopify.com/', password: 'skoday', category: 'Home & Living', profileName: 'WixBuddy', clientName: 'amir97470' },
  { id: 'sc-240', link: 'www.forgempire.com/', password: 'skayli', category: 'Jewelry', profileName: 'Manir', clientName: 'moeonline803' },
  { id: 'sc-241', link: 'wia11a-h6.myshopify.com/', password: 'skubre', category: 'Others', profileName: 'Wix_Buddy', clientName: 'cmerc3' },
  { id: 'sc-242', link: 'cutiessociety.com/', password: 'pawpod', category: 'Pet Products', profileName: 'Manir', clientName: 'primabintangk_' },
  { id: 'sc-243', link: 'proactivo.ec/', password: 'luwhee', category: 'Others', specialNote: 'Online Course', profileName: 'pro_wizards', clientName: 'martinborjap' },
  { id: 'sc-244', link: 'cozynestliving.ca/', category: 'Accessories', profileName: 'Webbrave Fiverr', clientName: 'ms3053957' },
  { id: 'sc-245', link: 'bevelandbond.com/', category: 'Kictchen Accessories', profileName: 'webbrave_Fiver', clientName: 'mofado77' },
  { id: 'sc-246', link: 'soleyredshoes.com/', category: 'Kictchen Accessories', profileName: 'wixbuddy_fiverr', clientName: 'eric61534' },
  { id: 'sc-247', link: 'ct1g5g-g0.myshopify.com/', password: 'yuimat', category: 'Jewelry', profileName: 'expo_web', clientName: 'krant24' },
  { id: 'sc-248', link: 'pronutraquest.eu/', category: 'Suppliment', profileName: 'Ecom geeky', clientName: 'hartmut2' },
  { id: 'sc-249', link: 'www.chestergems.com/', category: 'Jewelry', specialNote: 'store live', profileName: 'shopify_manir', clientName: 'chesterhome' },
  { id: 'sc-250', link: 'www.sensory-fragrance.com/', category: 'Perfume', specialNote: 'store live', profileName: 'shopify_manir', clientName: 'ismaelissack' },
  { id: 'sc-251', link: 'bakerstonechile.com/', category: 'Frutis', specialNote: 'Single store', profileName: 'pro_wizards', clientName: 'cristobal34' },
  { id: 'sc-252', link: 'www.skin-hause.com/', category: 'Beauty & Skincare', specialNote: 'store live', profileName: 'expo_web', clientName: 'prohaarexpert' },
  { id: 'sc-253', link: 'https://www.sierramadretortillas.com/pages/locations', password: 'habibi12317', category: 'Service' },
  { id: 'sc-254', link: 'lawntoolsstore.com/', category: 'Service' },
  { id: 'sc-255', link: '15faau-hr.myshopify.com/', password: 'chaith', category: 'Fashion & Apparel' },
  { id: 'sc-256', link: 'beannafashion.com/', password: 'reunte', category: 'Fashion & Apparel' },
  { id: 'sc-257', link: 'www.thehangoverpatches.com/', password: 'aunewy', category: 'Suppliment' },
  { id: 'sc-258', link: 'www.arovascent.com/', category: 'Beauty & Skincare' },
  { id: 'sc-259', link: 'velani-atelier.com/', password: '84982', category: 'Jewelry' },
  { id: 'sc-260', link: 'bark-n-bulk.myshopify.com/', category: 'Pet Products' },
  { id: 'sc-261', link: 'phorehim.org/', password: 'daobeg', category: 'Sports' },
  { id: 'sc-262', link: 'lifemadeeasy.com.lc/', category: 'Home & Living' },
  { id: 'sc-263', link: 'www.veloraonline.co.uk/', category: 'Perfume' },
  { id: 'sc-264', link: 'www.zamatacosmetics.co.za/', category: 'Hair and Beauty' },
  { id: 'sc-265', link: 'kovaoffroad.com/', category: 'Car accesories', profileName: 'Expo_web', clientName: 'inthevortex' },
  { id: 'sc-266', link: 'nouvellenaturals.com/', category: 'Beauty & Skincare', profileName: 'pro_wizards', clientName: 'ela_bil' },
  { id: 'sc-267', link: 'www.allaura.fr/', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 'allaura_m' },
  { id: 'sc-268', link: 'aquara.ch/', category: 'Home & Living', profileName: 'expo_web', clientName: 'jayddomingo' },
  { id: 'sc-269', link: 'drinknero.com/', category: 'Food & Beverage', profileName: 'expo_web', clientName: 'elliotk11' },
  { id: 'sc-270', link: 'cryolabs.ca/', password: 'nechog', category: 'Medicine', profileName: 'expo_web', clientName: 'crater79' },
  { id: 'sc-271', link: 'vyronhealth.shop/', category: 'Fitness & Health', profileName: 'pro_wizards', clientName: 'mohamedtaha337' },
  { id: 'sc-272', link: 'mabainaghareeb-2.myshopify.com/', password: 'owmawl', category: 'Accessories', profileName: 'WixBuddy', clientName: 'greyicket' },
  { id: 'sc-273', link: 'medonclick.com/', category: 'Fitness & Health', profileName: 'pro_wizards', clientName: 'garcel_one' },
  { id: 'sc-274', link: 'www.theoem.store/', category: 'Electronics & Gadgets', profileName: 'expo_web', clientName: 'danny163' },
  { id: 'sc-275', link: 'myscellanvinyl.com/', category: 'Music', profileName: 'Wix_buddy', clientName: 'keldan1' },
  { id: 'sc-276', link: 'larably', category: 'Fashion & Apparel', profileName: 'three_web', clientName: 'larably' },
  { id: 'sc-277', link: 'chaen-3.myshopify.com', password: 'baobli', category: 'Suppliment', profileName: 'wix_buddy', clientName: 'sara_nahj' },
  { id: 'sc-278', link: 'www.j11flowzathleisure.ca/', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 'gilansah' },
  { id: 'sc-279', link: 'www.brandengrave.com/', category: 'Fashion & Apparel', profileName: 'Upwork', clientName: 'Kumar' },
  { id: 'sc-280', link: 'rtfwti-i4.myshopify.com/', category: 'Kids & Baby Products', profileName: 'Pro_wizards', clientName: 'sikanderibrar' },
  { id: 'sc-281', link: 'little-readers-lane.myshopify.com', password: 'paifre', category: 'Kids & Baby Products', profileName: 'Ecom_geeky', clientName: 'sd_network' },
  { id: 'sc-282', link: 'www.athleticedgefashion.com/', category: 'Fashion & Apparel', profileName: 'expo_web', clientName: 'mzakirhossain' },
  { id: 'sc-283', link: 'downunder-dirtbikes.myshopify.com', password: 'Sahngray001', category: 'Bike Accessories', specialNote: '1000+ products', profileName: 'Webbrave', clientName: 'embo05' },
  { id: 'sc-284', link: 'mtpmkd-vp.myshopify.com', password: 'suisia', category: 'Home & Living', specialNote: 'Many type of product varients', profileName: 'Shopify Manir', clientName: 'smmjoe' },
  { id: 'sc-285', link: 'www.verlichtinggroothandel.nl', category: 'Docoration light', specialNote: '2500+ products', profileName: 'Pro wizerd', clientName: 'mautje0155' },
  { id: 'sc-286', link: 'moovogue.com', category: 'Fashion & Apparel', specialNote: 'Product Customized', profileName: 'Pro wizerd' },
  { id: 'sc-287', link: 'www.infillplans.com', category: 'Digital Products', specialNote: 'Architech Plan', profileName: 'Expo web', clientName: 'infillplans' },
  { id: 'sc-288', link: 'hectorsjewelry.com', category: 'Jewelry', profileName: 'Pro wizerd', clientName: 'hectorsjewelry' },
  { id: 'sc-289', link: 'ds1a0y-rf.myshopify.com/', password: 'rtawly', category: 'Beauty & Skincare', profileName: 'Shopify_Mainr', clientName: 'jamier302' },
  { id: 'sc-290', link: 'www.misstroy.com/', category: 'Bag', profileName: 'pro_wizards', clientName: 'misstroy97' },
  { id: 'sc-291', link: 'qwwbax-4x.myshopify.com', password: 'rtaube', category: 'Food & Beverage', profileName: 'Shopify_manir', clientName: 'bbmade15' },
  { id: 'sc-292', link: 'lathernlotion.myshopify.com/', password: 'shopify123', category: 'Perfume', profileName: 'Shopify_manir', clientName: 'curtisfrankl698' },
  { id: 'sc-293', link: 'jsmfqh-wb.myshopify.com/', password: 'naycle', category: 'Electronics & Gadgets', profileName: 'logic_lab', clientName: 'drewblendz' },
  { id: 'sc-294', link: 'lucebeauty.com', category: 'Beauty & Skincare', profileName: 'pro-wizards', clientName: 'sandy2020b' },
  { id: 'sc-295', link: 'slumbergirlsthelabel.co.uk/', category: 'Fashion & Apparel', profileName: 'pro-wizards', clientName: 'katyireson' },
  { id: 'sc-296', link: 'cake-rage-nyc.myshopify.com/', password: 'bawseb', category: 'Food & Beverage', profileName: 'Manir', clientName: 'cakeragenyc' },
  { id: 'sc-297', link: 'kutahyaporcelainusa.com/', password: 'supray', category: 'Home & Living', profileName: 'Manir' }
];
